version: '3.1'

services:

  db_bankline:
    image: postgres
    container_name: postgresql_container_api
    restart: always
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"